version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rdbg -n --open --host 0.0.0.0 --port 12345 -c -- bin/rails s -p 3000 -b 0.0.0.0"
    environment:
      WEB_CONCURRENCY: 0
      RAILS_ENV: development
      RUBYOPT: -W:deprecated
    ports:
      - 3000:3000
      - 12345:12345
    volumes:
      - .:/rails
      - ./docker/.bashrc:/root/.bashrc
      - ./docker/.bash_history:/root/.bash_history
      - ./docker/.irb_history:/root/.irb_history
      - bundle_vol:/usr/local/bundle
    tty: true
    stdin_open: true
volumes:
  bundle_vol:
